### ISSUE TITLE
Modify adapter on list of players in game to show achieved categories

### ISSUE THREAD

**Issue by pedrodaviddev** [Nhemesy/ITTrivial#32]
Show achieved categories with icons with yellow color and not achieved with gray color

Example:

![](https://cloud.githubusercontent.com/assets/15829524/26054211/0a9c87b6-396c-11e7-980f-9440cbd4046d.jpeg)

**Comment by bytemines** [comment]
Good Sketch, are you a magician?
![i_love_magic](https://cloud.githubusercontent.com/assets/16736700/26055635/019a1a06-3972-11e7-9f46-5486fe3e5865.gif)

**Comment by frnlpz** [comment]
I think it's better to show each achieved category with its own color, and not all of them with yellow, don't you think so?

**Comment by pedrodaviddev** [comment]
Okay, its a good idea. Anyway, if we dont like we will reject the pr 😆
