### ISSUE TITLE
Create nickname behavior on app

### ISSUE THREAD

**Issue by pedrodaviddev** [Nhemesy/ITTrivial#34]
We need an Singleton (kotlin object) to store the nickname of current player in app.
In the select nickname view the object must be initialized (setting the nickname) and must exist for all runtime.

**Comment by bytemines** [comment]
Why a singleton, which is the intention of being it.
Did you mean to do the persistence of a nickname?
@Nhemesy

**Comment by pedrodaviddev** [comment]
Yes @ConradoMateu. We need to store the username in all execution time

**Comment by bytemines** [comment]
We could use realm @Nhemesy

**Comment by pedrodaviddev** [comment]
Unnecessary @ConradoMateu
