### ISSUE TITLE
Create VIPER structure

### ISSUE THREAD

**Issue by pedrodaviddev** [Nhemesy/ITTrivial#8]
Create modules for clean mvp android structure and implement the basic logic in the project to show the mvp behavior

**Comment by bytemines** [comment]
![VIPER](https://s3.amazonaws.com/ckl-website-static/wp-content/uploads/2016/04/Viper-Module.png)

**Comment by bytemines** [comment]
V = View
I = Interactor
P = Presenter
E = Entity
R = Router

**Comment by bytemines** [comment]
![](https://media1.giphy.com/media/5hc2bkC60heU/giphy.gif)

**Comment by bytemines** [comment]
MVP + Interactor: https://gist.github.com/marciogranzotto/412c11947a311b65d75a8df5ad46b55d

VIPER: https://gist.github.com/marciogranzotto/1c96e87484a17bd914e159b2604e6469
